#!/bin/sh

sudo apt-get install -y podman
sudo wget https://github.com/containers/gvisor-tap-vsock/releases/download/v0.7.1/gvproxy-linux \
	-O /usr/libexec/podman/gvproxy &&
	sudo chmod +x /usr/libexec/podman/gvproxy
sudo chmod 4755 /usr/bin/newgidmap
sudo chmod 4755 /usr/bin/newuidmap
