#!/bin/sh

set -e

! test -d ~/.config && mkdir ~/.config
! test -d ~/.config/sioyek && mkdir ~/.config/sioyek

ln -sf "$PWD/prefs_user.config" ~/.config/sioyek/prefs_user.config
ln -sf "$PWD/keys_user.config" ~/.config/sioyek/keys_user.config
