#!/bin/sh

set -e

! test -d ~/.config && mkdir ~/.config
! test -d ~/.config/sketchybar && mkdir ~/.config/sketchybar

ln -sf "$PWD/sketchybarrc" ~/.config/sketchybar/sketchybarrc
ln -sf "$PWD/sketchybarrc.mba" ~/.config/sketchybar/sketchybarrc.mba
ln -sf "$PWD/plugins" ~/.config/sketchybar/plugins

brew services restart sketchybar
