#!/usr/bin/env bash

#FONT="Terminess Nerd Font"
FONT="Unifont"
# FONT="Roboto Mono Nerdfont"
# FONT="IBM Plex Mono"
# BACKGROUND="0xff222222"
BACKGROUND="0xff101010"
BACKGROUND_SELECTED="0xff2A4383"

# FOREGROUND="0xff999999"
FOREGROUND="0xffcccccc"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

HEIGHT=18

##### Adding Main Bar #####

bar=(
  # color=0xff000000
  color=0xff2A4383
  height="$HEIGHT"
  position=top
  sticky=on
  # padding_left=10
  # padding_right=10
  padding_left=0
  padding_right=0
)

default=(
  icon.font="$FONT:Regular:16.0"
  icon.color="$FOREGROUND"
  label.font="$FONT:Regular:16.0"
  label.color="$FOREGROUND"
  padding_left=0
  padding_right=0
  label.padding_left=0
  label.padding_right=0
  # icon.padding_left=10
  # icon.padding_right=10
  icon.padding_left=8
  icon.padding_right=8
)

##### Adding Space Items #####

sketchybar \
  --bar "${bar[@]}" \
  --default "${default[@]}"

SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9")

spaces=()
for i in "${!SPACE_ICONS[@]}"
do
  sid=$(($i+1))
  spaces+=(space."$sid")
  sketchybar --add space space.$sid left \
    --set space.$sid associated_space=$sid \
    icon="${SPACE_ICONS[i]}" \
    background.corner_radius=0 \
    background.height="$HEIGHT" \
    background.color=$BACKGROUND_SELECTED \
    background.drawing=off \
    label.drawing=off \
    script="$PLUGIN_DIR/space.sh" \
    click_script="yabai -m space --focus $sid"
done

##### Adding Left Items #####

sketchybar \
  --add item space_separator left \
  --set space_separator icon="[]="

#   sketchybar \
  #   --add item focus left \
  #   --set focus script="$PLUGIN_DIR/focus.sh" \
  #   --set focus update_freq=1 \
  #   label.color="0xfffefeff" \
  #   --subscribe focus front_app_switched
# # background.color="$BACKGROUND_SELECTED" \
  #   # background.corner_radius=0 \
  #   # background.height="$HEIGHT"

sketchybar \
  --add item focus left \
  --set focus script='sketchybar --set $NAME label="$(yabai -m query --windows --window | jq -r '.title')"' \
  --set focus update_freq=1 \
  label.color="0xfffefeff" \
  --subscribe focus front_app_switched

sketchybar \
  --add bracket spaces "${spaces[@]}" space_separator \
  --set spaces background.color="$BACKGROUND" \
  background.corner_radius=0 \
  background.height="$HEIGHT"

##### Adding Right Items #####

# sketchybar \
  #   --add item clock right \
  #   --set clock update_freq=1 \
  #   script="$PLUGIN_DIR/clock.sh" \
  #   background.color="$BACKGROUND" \
  #   background.corner_radius=0 \
  #   background.height="$HEIGHT"

sketchybar \
  --add item clock right \
  --set clock script='sketchybar --set "$NAME" label="$(date)"' \
  --set clock update_freq=1 \
  background.color="$BACKGROUND" \
  background.corner_radius=0 \
  background.height="$HEIGHT"

sketchybar \
  --add item wifi right \
  --set wifi script="$PLUGIN_DIR/wifi.sh" \
  icon="NET" \
  background.color="$BACKGROUND" \
  background.corner_radius=0 \
  background.height="$HEIGHT" \
  --subscribe wifi wifi_change

sketchybar \
  --add item battery right \
  --set battery script="$PLUGIN_DIR/battery.sh" \
  update_freq=120 \
  background.color="$BACKGROUND" \
  background.corner_radius=0 \
  background.height="$HEIGHT" \
  --subscribe battery system_woke power_source_change

sketchybar --update
