#!/bin/sh

# see this wiki page for information:
# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist >/dev/null 2>&1 &

sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa && sleep 1 && yabai -m config window_shadow off"

# yabai -m config \
# 	layout bsp \
# 	top_padding 0 \
# 	bottom_padding 0 \
# 	left_padding 0 \
# 	right_padding 0 \
# 	window_gap 0 \
# 	external_bar all:18:0 \
# 	mouse_follows_focus off \
# 	focus_follows_mouse off \
# 	window_topmost off \
# 	window_opacity off \
# 	window_shadow off \
# 	window_border off \
# 	window_border_width 1 \
# 	active_window_opacity 1.0 \
# 	normal_window_opacity 1.0 \
# 	split_ratio 0.50 \
# 	window_animation_duration 0.0 \
# 	auto_balance off \
# 	mouse_modifier alt \
# 	mouse_action1 move \
# 	mouse_action2 resize \
# 	mouse_drop_action swap

# yabai -m space --toggle padding
# yabai -m space --toggle gap

yabai -m config \
	layout bsp \
	top_padding 0 \
	bottom_padding 0 \
	left_padding 0 \
	right_padding 0 \
	window_gap 0 \
	external_bar all:18:0 \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_opacity off \
	window_shadow off \
	active_window_opacity 1.0 \
	normal_window_opacity 1.0 \
	split_ratio 0.50 \
	window_animation_duration 0.0 \
	auto_balance off \
	mouse_modifier alt \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap
# window_topmost off \
# window_border off \
# window_border_width 1 \

yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Settings$" manage=off
yabai -m rule --add app="^Preferences$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^About$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^Digital Colour Meter$" manage=off
yabai -m rule --add app="^Digital Color Meter$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add title="Settings$" manage=off
yabai -m rule --add title="Preferences$" manage=off
yabai -m rule --add title="Archive Utility$" manage=off

echo "yabai configuration loaded.."
