#!/bin/sh

set -e

! test -d ~/.local && mkdir ~/.local
! test -d ~/.local/share && mkdir ~/.local/share
! test -d ~/.local/share/docker && mkdir ~/.local/share/docker

ln -sf "$PWD/completion" ~/.local/share/docker/completion
