#!/bin/sh

# A list of all built-in modifier and literal keywords can
# be found at https://github.com/koekeishiya/skhd/issues/1

# -- Navigation --
# space navigation
lalt - 1 : yabai -m space --focus 1
lalt - 2 : yabai -m space --focus 2
lalt - 3 : yabai -m space --focus 3
lalt - 4 : yabai -m space --focus 4
lalt - 5 : yabai -m space --focus 5
lalt - 6 : yabai -m space --focus 6
lalt - 7 : yabai -m space --focus 7
lalt - 8 : yabai -m space --focus 8
lalt - 9 : yabai -m space --focus 9
lalt - tab : yabai -m space --focus recent

# window navigation
lalt - h : yabai -m window --focus west
lalt - j : yabai -m window --focus south
lalt - k : yabai -m window --focus north
lalt - l : yabai -m window --focus east

# float / unfloat window
lalt + shift - space : yabai -m window --toggle float --grid 4:4:1:1:2:2

# zoom window
lalt - m : yabai -m window --toggle zoom-fullscreen

# zoom window native
lalt + shift - m : yabai -m window --toggle native-fullscreen

# toggle layout
lalt - t : yabai -m space --layout bsp
lalt - f : yabai -m space --layout float
lalt - space : yabai -m space --layout "$(yabai -m query --spaces --space | jq -r 'if .type == "bsp" then "float" else "bsp" end')"

# close focused window
lalt + shift - c : yabai -m window --close

# -- Window Movement --
# window movement in spaces
shift + lalt - h : yabai -m window --warp west
shift + lalt - j : yabai -m window --warp south
shift + lalt - k : yabai -m window --warp north
shift + lalt - l : yabai -m window --warp east

# toggle split orientation of the selected windows node
shift + lalt - s : yabai -m window --toggle split

# window movement between spaces
#lalt + shift - m : yabai -m window --space last; yabai -m space --focus last
lalt + shift - p : yabai -m window --space prev && yabai -m space --focus prev
lalt + shift - n : yabai -m window --space next && yabai -m space --focus next
lalt + shift - 1 : yabai -m window --space 1 && yabai -m space --focus 1
lalt + shift - 2 : yabai -m window --space 2 && yabai -m space --focus 2
lalt + shift - 3 : yabai -m window --space 3 && yabai -m space --focus 3
lalt + shift - 4 : yabai -m window --space 4 && yabai -m space --focus 4
lalt + shift - 5 : yabai -m window --space 5 && yabai -m space --focus 5
lalt + shift - 6 : yabai -m window --space 6 && yabai -m space --focus 6
lalt + shift - 7 : yabai -m window --space 7 && yabai -m space --focus 7
lalt + shift - 8 : yabai -m window --space 8 && yabai -m space --focus 8
lalt + shift - 9 : yabai -m window --space 9 && yabai -m space --focus 9

# mirror space on x and y axis
shift + lalt - x : yabai -m space --mirror x-axis
shift + lalt - y : yabai -m space --mirror y-axis

# -- Resize --
# equalize size of windows
lalt - e : yabai -m space --balance

# enable / disable gaps in current workspace: ctrl + lalt - g
lalt - g : yabai -m space --toggle padding && yabai -m space --toggle gap

# Resize windows: ctrl + lalt - {h, j, k, l}
lalt + ctrl - h : yabai -m window --resize right:-100:0 || yabai -m window --resize left:-100:0
lalt + ctrl - j : yabai -m window --resize bottom:0:100 || yabai -m window --resize top:0:100
lalt + ctrl - k : yabai -m window --resize bottom:0:-100 || yabai -m window --resize top:0:-100
lalt + ctrl - l : yabai -m window --resize right:100:0 || yabai -m window --resize left:100:0

# -- Misc --
# new window in hor./ vert. splits for all applications with yabai
lalt - s : yabai -m window --insert east && skhd -k "cmd - n"
lalt - v : yabai -m window --insert south && skhd -k "cmd - n"

# restart yabai & sketchybar
lalt - r : yabai --restart-service && skhd -r && skhd --restart-service && brew services restart sketchybar
#ctrl + lalt - r : yabai --restart-service && sketchybar --reload "$HOME/.config/sketchybar/sketchybarrc.mba" && skhd --restart-service && skhd -r

# launch pass menu script
#lalt + shift - d : export app_id="$(osascript -e "path to frontmost application as text" 2>/dev/null)"; alacritty --title "Passmenu" --config-file "$(readlink -f "$HOME/.config/alacritty/pass-alacritty-config.yml")" -e "$HOME/Scripts/passmenu"
lalt + shift - d : export app_id="$(osascript -e "path to frontmost application as text" 2>/dev/null)" && alacritty --title "Passmenu" \
	--config-file "$(readlink -f "$HOME/.config/alacritty/pass-alacritty-config.toml")" \
	-e "$HOME/Scripts/passmenu"

# open terminal
lalt + shift - return : /Applications/Alacritty.app/Contents/MacOS/alacritty >/dev/null 2>&1
