#!/bin/sh

set -e

! test -d ~/.config && mkdir ~/.config
! test -d ~/.config/newsboat && mkdir ~/.config/newsboat

ln -sf "$PWD/config" ~/.config/newsboat/config
ln -sf "$PWD/urls" ~/.config/newsboat/urls
