#!/bin/bash
set -e

user=rwxrob
name=keg
target="$HOME/.local/bin"

os=$(uname -s | tr '[:upper:]' '[:lower:]')
arch=$(uname -m)
[[ $arch = x86_64 ]] && arch=amd64
[[ $arch = aarch64 ]] && arch=arm64

if [[ $os = linux && $arch = arm64 ]]; then
	echo "Precompiled binary unavailable"
	echo "Do instead:"
	echo "    go install github.com/rwxrob/keg/cmd/keg@latest"
	exit
fi

latest="https://api.github.com/repos/${user}/${name}/releases/latest"
ver=$(curl -sS "$latest" | jq -r .zipball_url) && test -n "$ver"
ver=${ver##*/}
ver=${ver#v}
exe="${name}-${os}-${arch}"
url="https://github.com/${user}/${name}/releases/download/v${ver}/${exe}"
mkdir -p "$target" || true
cd "$target"
curl -LO "$url"
chmod ug+x "$exe"
mv "$exe" "$name"
