#!/bin/sh

# Resources:
#   - https://github.com/chaudhryjunaid/setup-my-linux/blob/main/roles/dnf/vars/main.yml

# TODO: Fix this

sudo dnf -y install autoconf
sudo dnf -y install automake
sudo dnf -y install binutils
sudo dnf -y install bison
sudo dnf -y install flex
sudo dnf -y install gcc
sudo dnf -y install gcc-c+
sudo dnf -y install glibc-devel
sudo dnf -y install libtool
sudo dnf -y install make
sudo dnf -y install cmake
sudo dnf -y install clang
sudo dnf -y install gdb
sudo dnf -y install entr
sudo dnf -y install autoconf
sudo dnf -y install parallel
sudo dnf -y install bash-completion

sudo dnf -y install wl-clipboard

# git
sudo dnf -y install git
sudo dnf -y install git-lfs
sudo dnf -y install git-annex
sudo dnf -y install git-crypt
sudo dnf -y install git-remote-gcrypt

# pandoc
sudo dnf -y install pandoc
sudo dnf -y install pandoc-latex

sudo dnf -y install ansible
sudo dnf -y install gcc
sudo dnf -y install make
sudo dnf -y install cmake
sudo dnf -y install gdb
sudo dnf -y install vim-enhanced
sudo dnf -y install tmux
sudo dnf -y install lynx
sudo dnf -y install man-pages
sudo dnf -y install clang-tools-extra
sudo dnf -y install nmap
sudo dnf -y install jq

sudo dnf -y install dnf-plugins-core

sudo dnf -y install podman
sudo dnf -y install qemu
sudo dnf -y install qemu-kvm # ?
# sudo dnf -y groupinstall "Headless Virtualization" # ??

sudo dnf -y install golang

sudo dnf -y group install "Development Tools"
sudo dnf -y group install "Sway Desktop"

sudo dnf -y inntall terminus-fonts
sudo dnf -y inntall terminus-fonts-console
sudo dnf -y inntall alacritty

sudo dnf -y group install "Development Libraries"
sudo dnf -y group install "C Development Tools and Libraries"
sudo dnf -y group install "ARM Tools"
sudo dnf -y group install "Perl Development"
