#!/usr/bin/env bash

# Convert a specified amount from one currency to another using the
# exchangerate-api.com service. Assumes either the API key is stored in
# the environment variable EXCHANGERATE_API_KEY or in a passwordstore
# accessible via gopass.

_have() { type "$1" &>/dev/null; }

if [[ $# -ne 3 ]]; then
	echo "Usage: ${0##*/} <from_currency> <to_currency> <amount>" >&2
	exit 1
fi

! _have jq && echo "Requires jq" >&2 && exit 1
! _have curl && echo "Requires curl" >&2 && exit 1
! _have gopass && echo "Requires gopass" >&2 && exit 1

export_key() {
	local env=$1 secret=$2 key=$3 value
	if [[ -z "${!env}" ]]; then
		value=$(gopass show -o "$(gopass ls --flat | grep -m1 "^$secret")" "$key" 2>/dev/null) || {
			echo "Error: Failed to retrieve key from password store" >&2
			return 1
		}
		export "$env=$value"
	fi
}

from_currency=${1^^}
to_currency=${2^^}
amount=$3

export_key "EXCHANGERATE_API_KEY" "exchangerate-api.com" "api" || exit 1
response=$(curl -s "https://v6.exchangerate-api.com/v6/${EXCHANGERATE_API_KEY}/latest/${from_currency}")
exchange_rate=$(jq -r --arg currency "$to_currency" '.conversion_rates[$currency]' <<<"$response")

if [[ -z "$exchange_rate" || "$exchange_rate" == null ]]; then
	echo "Error: Currency or exchange rate not found" >&2
	exit 1
fi

bc <<<"scale=4; $amount * $exchange_rate"
