#!/usr/bin/env bash

_have() { type "$1" &>/dev/null; }

figid() {
	! _have identify && "requires ImageMagick" && exit 1
	identify -format "F$(date -u +%Y%m%d%H%M%SZ -r "$1")-%G.%e" "$1"
}

figid "$@"
