#!/bin/bash

figname() {
	# TODO check for existence of identify
	local w h file suf
	file=${1##*/}
	suf=${file##*.}
	w=$(identify -format "%w" "$1")
	h=$(identify -format "%h" "$1")
	printf "fig-%sx%s.%s" "$w" "$h" "$suf"
}

figname "$@"
