#!/usr/bin/env bash

count=1
if test -n "$1"; then
	count="$1"
fi

IFS=$'\n'
mapfile -t html < <(tail -n "${count}" ~/.lynx_bookmarks.html | pandoc -f html -t markdown --wrap=none)

for line in "${html[@]}"; do
	if [[ $line =~ ^\[(.+)\]\((.+)\) ]]; then
		line=${line/](/]: <}
		line=${line/%)/>}
		echo "$line"
	fi
done
