#!/bin/sh

set -e

confd="$PDFS"
cmds="open help list ls"

help() {
	echo "Usage: ${0##*/} [open|ls|help] [<pdf>]"
}

open() {
	pdf="${confd}/${1}.pdf"
	if [ -f "$pdf" ]; then
		command open "$pdf"
	else
		echo "Error: $1 not found" >&2
	fi
}

list() {
	while read -r line; do
		line=${line##*/}
		echo "${line%.pdf}"
	done <<EOF
$(ls -1 "${confd}"/*.pdf)
EOF
}

# ---------------------- bash completion context ---------------------

# add `complete -C pdf pdf` to bashrc

if [ -n "${COMP_LINE}" ]; then
	pre="${COMP_LINE##* }"
	for c in ${cmds:+${cmds} $(list)}; do
		[ -z "${pre}" -o "${c}" != "${c#${pre}}" ] && echo "$c"
	done
	exit
fi

# ------------------------------- main -------------------------------

[ $# -eq 0 ] && help && exit 0
case "$1" in
help) help ;;
ls | list) list ;;
open) open "$2" ;;
*) open "$1" ;;
esac
