#!/usr/bin/env python3

import http.server
import os
import urllib


class MyHTTPRequestHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        urlparts = urllib.parse.urlparse(self.path)
        request_file_path = urlparts.path.strip('/')

        if not any(request_file_path.endswith(x) for x in ['.html', '.htm']):
            if os.path.exists(request_file_path + '.html'):
                self.path += '.html'

        return super().do_GET()


def run_server():
    http.server.test(HandlerClass=MyHTTPRequestHandler)


if __name__ == '__main__':
    run_server()
