return {
	-- "kyazdani42/nvim-tree.lua",
	-- version = "*",
	-- lazy = true,
	-- -- event = "VimEnter",
	-- keys = { { "<leader>n", "<cmd>NvimTreeToggle<cr>" } },
	-- config = function()
	-- 	-- vim.keymap.set("n", "<leader>n", ":NvimTreeToggle<cr>")
	--
	-- 	require("nvim-tree").setup({
	-- 		update_focused_file = {
	-- 			enable = true,
	-- 			update_cwd = true,
	-- 		},
	-- 		actions = {
	-- 			open_file = {
	-- 				window_picker = {
	-- 					enable = false,
	-- 				},
	-- 			},
	-- 		},
	-- 		renderer = {
	-- 			icons = {
	-- 				show = {
	-- 					file = false,
	-- 					folder = false,
	-- 					folder_arrow = true,
	-- 					git = false,
	-- 				},
	-- 				glyphs = {
	-- 					folder = {
	-- 						arrow_closed = "+",
	-- 						arrow_open = "-",
	-- 					},
	-- 				},
	-- 			},
	-- 		},
	-- 		view = {
	-- 			signcolumn = "no",
	-- 		},
	-- 	})
	-- end,
}
