# https://alacritty.org/config-alacritty.html

import = ["~/.config/alacritty/theme.toml"]

# [colors]
# draw_bold_text_with_bright_colors = true

[window]
dimensions = { columns = 130, lines = 40 }
dynamic_padding = true
decorations = "None"                       # "Full" | "None"
dynamic_title = false

[scrolling]
history = 100000

[font]
size = 12.6
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
# normal = { family = "Monospace", style = "Regular" }
normal = { family = "Berkeley Mono", style = "Regular" }

[cursor]
style = { shape = "Block", blinking = "Off" }
