[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.primary]
background = "#0e0a00"
foreground = "#cfcfcf"

[colors.normal]
black = "#000000"
red = "#dc3c3c"
green = "#95c76f"
yellow = "#d28e5d"
blue = "#8485ce"
magenta = "#b73999"
cyan = "#00aba5"
white = "#666666"

[colors.bright]
black = "#4a4a4a"
red = "#ff7c7c"
green = "#d5ffaf"
yellow = "#ffce9d"
blue = "#c4c5ff"
magenta = "#f779d9"
cyan = "#40ebe5"
white = "#ffffff"
