#!/bin/sh

set -e

! test -d ~/.local && mkdir ~/.local
! test -d ~/.local/share && mkdir ~/.local/share
! test -d ~/.local/share/podman && mkdir ~/.local/share/podman

ln -sf "$PWD/completion" ~/.local/share/podman/completion
