#!/bin/sh

set -e

! test -d ~/.config && mkdir ~/.config
! test -d ~/.config/lynx && mkdir ~/.config/lynx

ln -sf "$PWD/lynx.cfg" ~/.config/lynx/lynx.cfg
ln -sf "$PWD/lynx.lss" ~/.config/lynx/lynx.lss
